### ISSUE TITLE
トリミングされることによるアニメーションのズレについて

### ISSUE THREAD

**Issue by M-Kanou** [SpriteStudio/CellAnimeTool#1]
お世話になっております。

CellAnimeToolを使わせていただいたのですが、
コンバートして作成されたプロジェクトファイルを開いてアニメーションを再生すると、
アニメーションの見た目（キャラクターの位置）が、
画像がトリミングされることにより中心点がずれて毎フレームのキャラの位置がズレるような感じに
なります。

画像がトリミングされた状態でセルリストが作成されるのは仕様だとは思うのですが、
それによる毎フレームの見た目のズレを解消する方法は何かございますでしょうか？

【動作環境】
OS：Mac OS X Yosemite 10.10.3
SpriteStudio：5.3.6.5276

**Comment by DKAlpha** [comment]
透明部分をトリミングしても元画像の中心がSS上の中心に会う様に配置されるのが意図している動作になります。
こちらで動作検証しますのでしばらくお待ちください。
進展がありましたｒこちらで報告いたします。

**Comment by DKAlpha** [comment]
現象を確認して修正しました。再度取得して使ってみてください。
お手数ではございますが問題が無い様であればお知らせいただけると助かります。

**Comment by M-Kanou** [comment]
ご回答ありがとうございます。

修正対応くださり、誠にありがとうございます。
こちらでも正常にアニメーションしているのを確認いたしました。

以上、よろしくお願いいたします。
